version: "3"

services:
  app:
    container_name:  material_app
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
      - ./tests:/app/tests
      - ./material:/app/material
      - ./docker:/app/docker
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
