version: "3"

services:
  app:
    build:
      context: .
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app
      - ./tests:/app/tests
      - ./material:/app/material
      - ./docker:/app/docker
    environment:
      - DB_HOST=db
      - DB_NAME=app
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword
